package com.network.common;

public class UriPortsBaseNames {

	public static final String BASE_TERMINAL_NODE_REGISTRATION_OUTBOUND_PORT_URI = "TERMINAL_NODE_REGISTRATION_OUTBOUND_PORT_URI";
	public static final String BASE_TERMINAL_NODE_COMMUNICATION_INBOUND_PORT_URI = "TERMINAL_NODE_COMMUNICATION_INBOUND_PORT_URI";
	public static final String BASE_TERMINAL_NODE_COMMUNICATION_OUTBOUND_PORT_URI = "TERMINAL_NODE_COMMUNICATION_OUTBOUND_PORT_URI";

	public static final String BASE_ACCESS_POINT_NODE_REGISTRATION_OUTBOUND_PORT_URI = "ACCESS_POINT_NODE_REGISTRATION_OUTBOUND_PORT_URI";
	public static final String BASE_ACCESS_POINT_NODE_COMMUNICATION_INBOUND_PORT_URI = "ACCESS_POINT_NODE_COMMUNICATION_INBOUND_PORT_URI";
	public static final String BASE_ACCESS_POINT_NODE_COMMUNICATION_OUTBOUND_PORT_URI = "ACCESS_POINT_NODE_COMMUNICATION_OUTBOUND_PORT_URI";
	public static final String BASE_ACCESS_POINT_NODE_ROUTING_INBOUND_PORT_URI = "ACCESS_POINT_NODE_ROUTING_INBOUND_PORT_URI";

	public static final String BASE_ROUTING_NODE_REGISTRATION_OUTBOUND_PORT_URI = "ROUTING_NODE_REGISTRATION_OUTBOUND_PORT_URI";
	public static final String BASE_ROUTING_NODE_COMMUNICATION_INBOUND_PORT_URI = "ROUTING_NODE_COMMUNICATION_INBOUND_PORT_URI";
	public static final String BASE_ROUTING_NODE_COMMUNICATION_OUTBOUND_PORT_URI = "ROUTING_NODE_COMMUNICATION_OUTBOUND_PORT_URI";
	public static final String BASE_ROUTING_NODE_ROUTING_INBOUND_PORT_URI = "ROUTING_NODE_ROUTING_INBOUND_PORT_URI";

	public static final String BASE_REGISTER_REGISTRATION_INBOUND_PORT_URI = "REGISTER_REGISTRATION_INBOUND_PORT_URI";

}
